ALTER TABLE SPECIFIC_SERVICE ADD N_ESTADO varchar(20);
ALTER TABLE SPECIFIC_SERVICE ADD N_ING_SOL varchar(100);
ALTER TABLE SPECIFIC_SERVICE ADD N_PROYECTO varchar(100);
ALTER TABLE SPECIFIC_SERVICE ADD N_CRQ varchar(50);
